CONFIG_NAME: 'finegan_train'
DATASET_NAME: 'birds'
DATA_DIR: ''
SAVE_DIR: ''
GPU_ID: '0'
WORKERS: 4

SUPER_CATEGORIES: 20   # For CUB 
FINE_GRAINED_CATEGORIES: 200  # For CUB
TIED_CODES: True   # Do NOT change this to False during training.

TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    BATCH_SIZE: 16
    MAX_EPOCH: 600
    HARDNEG_MAX_ITER: 1500
    SNAPSHOT_INTERVAL: 4000
    SNAPSHOT_INTERVAL_HARDNEG: 500
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002

GAN:
    DF_DIM: 64
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2
