runtime:
  all_reduce_alg: null
  batchnorm_spatial_persistent: false
  dataset_num_private_threads: null
  default_shard_dim: -1
  distribution_strategy: mirrored
  enable_xla: false
  gpu_thread_mode: null
  loss_scale: null
  mixed_precision_dtype: float32
  num_cores_per_replica: 1
  num_gpus: 1
  num_packs: 1
  per_gpu_thread_count: 0
  run_eagerly: false
  task_index: -1
  tpu: null
  tpu_enable_xla_dynamic_padder: null
  use_tpu_mp_strategy: false
  worker_hosts: null
task:
  allow_image_summary: false
  differential_privacy_config: null
  init_checkpoint: gs://ghpark-imagenet-tfrecord/ckpt/resnet50_imagenet
  init_checkpoint_modules: backbone
  losses:
    background_cls_weight: 0.2
    lambda_box: 5.0
    lambda_cls: 1.0
    lambda_ins: 1.0
  model:
    backbone:
      resnet:
        bn_trainable: false
        depth_multiplier: 1.0
        model_id: 50
        replace_stem_max_pool: false
        resnetd_shortcut: false
        scale_stem: true
        se_ratio: 0.0
        stem_type: v0
        stochastic_depth_drop_rate: 0.0
      type: resnet
    backbone_endpoint_name: '5'
    decoder:
      fpn:
        fusion_type: sum
        num_filters: 256
        use_keras_layer: false
        use_separable_conv: false
      type: fpn
    hidden_size: 256
    input_size: [128, 128, 3]
    max_level: 5
    min_level: 2
    norm_activation:
      activation: relu
      norm_epsilon: 0.001
      norm_momentum: 0.99
      use_sync_bn: true
    num_classes: 2
    num_decoder_layers: 6
    num_encoder_layers: 6
    num_queries: 10
    roi_size: 128
  name: null
  per_category_metrics: false
  train_data:
    apply_tf_data_service_before_batching: false
    autotune_algorithm: null
    block_length: 1
    cache: false
    cycle_length: null
    decoder:
      simple_decoder:
        attribute_names: []
        mask_binarize_threshold: null
        regenerate_source_id: false
      type: simple_decoder
    deterministic: null
    drop_remainder: true
    dtype: float32
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    file_type: tfrecord
    global_batch_size: 32
    input_path: /data2/cityscale/tfrecord/train-noise*
    is_training: true
    prefetch_buffer_size: null
    ram_budget: null
    seed: null
    sharding: true
    shuffle_buffer_size: 1000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: ''
    tfds_skip_decoding_feature: ''
    tfds_split: train
    trainer_id: null
  validation_data:
    apply_tf_data_service_before_batching: false
    autotune_algorithm: null
    block_length: 1
    cache: false
    cycle_length: null
    decoder:
      simple_decoder:
        attribute_names: []
        mask_binarize_threshold: null
        regenerate_source_id: false
      type: simple_decoder
    deterministic: null
    drop_remainder: false
    dtype: float32
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    file_type: tfrecord
    global_batch_size: 16
    input_path: /data2/cityscale/tfrecord/train-noise*
    is_training: false
    prefetch_buffer_size: null
    ram_budget: null
    seed: null
    sharding: true
    shuffle_buffer_size: 10000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: ''
    tfds_skip_decoding_feature: ''
    tfds_split: train
    trainer_id: null
trainer:
  allow_tpu_summary: false
  best_checkpoint_eval_metric: AP
  best_checkpoint_export_subdir: best_ckpt
  best_checkpoint_metric_comp: higher
  checkpoint_interval: 13129
  continuous_eval_timeout: 3600
  eval_tf_function: true
  eval_tf_while_loop: false
  loss_upper_bound: 1000000.0
  max_to_keep: 1
  optimizer_config:
    ema: null
    learning_rate:
      polynomial:
        cycle: false
        decay_steps: 131290
        end_learning_rate: 1.0e-06
        initial_learning_rate: 0.0001
        name: PolynomialDecay
        offset: 0
        power: 1.0
      type: polynomial
    optimizer:
      adamw_experimental:
        amsgrad: false
        beta_1: 0.9
        beta_2: 0.999
        clipnorm: null
        clipvalue: null
        epsilon: 1.0e-08
        global_clipnorm: -1.0
        jit_compile: false
        name: AdamWeightDecayExperimental
        weight_decay: 1.0e-05
      type: adamw_experimental
    warmup:
      linear:
        name: linear
        warmup_learning_rate: 0
        warmup_steps: 26258
      type: linear
  preemption_on_demand_checkpoint: true
  recovery_begin_steps: 0
  recovery_max_trials: 0
  steps_per_loop: 13129
  summary_interval: 13129
  train_steps: 656450
  train_tf_function: true
  train_tf_while_loop: true
  validation_interval: 13129
  validation_steps: 312
  validation_summary_subdir: validation
