name: lint_python
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - run: pip install flake8
      - run: flake8 . --count --show-source --statistics  --select=E9,F63  # ,F7,F82 
